using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        public int Q101 = 0;
        public int Q102 = 0;
        public int Q103 = 0;
        public int Q104 = 0;
        public int Q105 = 0;
        public int Q106 = 0;
        public int Q107 = 0;
        public Vector3 Q11pose = new Vector3(0f, 0f, 0f);
        public Vector3 Q12pose = new Vector3(0f, 0f, 0f);
        public Vector3 Q13pose = new Vector3(0f, 0f, 0f);
        public Vector3 Q14pose = new Vector3(0f, 0f, 0f);
        public Vector3 Q15pose = new Vector3(0f, 0f, 0f);
        public Vector3 Q16pose = new Vector3(0f, 0f, 0f);
        public Vector3 Q17pose = new Vector3(0f, 0f, 0f);
        public int Q18pose = 0;
    }
}
